apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: 0x696d/hipster-frontend:v0.0.1
    name: frontend
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "192.168.1.100"
    - name: CURRENCY_SERVICE_ADDR
      value: "192.168.1.101"
    - name: CART_SERVICE_ADDR
      value: "192.168.1.106"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "192.168.1.102"
    - name: CHECKOUT_SERVICE_ADDR
      value: "192.168.1.103"
    - name: SHIPPING_SERVICE_ADDR
      value: "192.168.1.104"
    - name: AD_SERVICE_ADDR
      value: "192.168.1.105"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
