apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: 0x696d/hipster-frontend:v0.0.1
    name: frontend
  dnsPolicy: ClusterFirst
  restartPolicy: Never
